### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by mdehollander** [nwnoll/taxalogue#11]
Hi @nwnoll,

I am giving this tool a try, but end up with some installation issue:

```
An error occurred while installing bigdecimal (3.1.8), and Bundler cannot continue.

In Gemfile:
  bigdecimal
```

I see the depedencybot also create a PR: #10 

When I try that branch I get this error:

```
An error occurred while installing strscan (3.1.0), and Bundler cannot continue.

In Gemfile:
  rexml was resolved to 3.3.3, which depends on
    strscan
```

Can you confirm the current Gemfile works? How should I resolve the dependency issues I get?

**Comment by nwnoll** [comment]
Hi and thanks for reporting!

I saw a related issue for bigdecimal 3.1.7, where installing some dependencies solved the issue, maybe that will help? I would try it without the PR10: https://github.com/academicpages/academicpages.github.io/issues/2061#issuecomment-2067289135

If this does not solve the issue, it might be good to know what happens and what kind of errors you get if you try to install bigdecimal manually via `gem install bigdecimal` and also which ruby version/OS you are using.

**Comment by mdehollander** [comment]
Figure out there was a compilation issue before it printed a lot of dependency issues:

```
make: x86_64-conda-linux-gnu-cc: Command not found  
```
You see I installed ruby using conda. When installing gxx_linux-64 it could compile and install everything. Now the main taxalogue.rb runs. :tada:

**Comment by nwnoll** [comment]
Ok, cool that you could solve it! I will close this Issue for now, if you run into any other problem, please consider opening a new Issue.
